### ISSUE TITLE
make !help support other languages

### ISSUE THREAD

**Issue by zodman** [facebook/pyaib#11]
like

!ayuda

i think need change it:

https://github.com/facebook/pyaib/blob/master/pyaib/components.py#L219

**Comment by fried** [comment]
Your best bet is to monkey patch those decorators in your entry point.  Also you can just add a handler for !ayuda that calls the standard !help handler. 

But there is no reason we could not look in the context for a help word. 
We accept pull requests

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
