### ISSUE TITLE
Support live plugin reload

### ISSUE THREAD

**Issue by andreimarcu** [facebook/pyaib#12]
Being able to modify(/add/remove?) a plugin without restarting a bot would be pretty sweet.

This is how phenny does it, for reference:
https://github.com/sbp/phenny/blob/master/modules/reload.py

Is this something you would be interested in adding?

**Comment by fried** [comment]
We will have to keep track of all the event watches and timers, so they can be deleted when the plugin is removed. 
I guess we could do this by examining the callbacks to see if they belong to a plugin and remove them.  

We would gladly accept a pull request to add this support?,  But it serves little purpose for our (facebook) use cases today.
