### ISSUE TITLE
Not able to modify config

### ISSUE THREAD

**Issue by rossjrw** [facebook/pyaib#21]
I'm looking to bind the nickserv password to a command line argument so I can upload the config to a public github without fear of my bot's IRC registration being stolen.

In `bot.py` (as per the example setup) I've used the `argparse` module to take a password argument. I've also removed the nickserv component in `bot.conf` and added a nickserv plugin, which is just a duplicate of the nickserv component except it runs a `print` after sending the IDENTIFY to nickserv just to confirm that it got the password right.

In `bot.conf`, I set the default password in `password` in `plugin.nickserv` to "hunter2".

In `bot.py`, before I do `bot.run()`, I do `bot.config.plugin.nickserv.password = args.password`. I print `bot.config` before and after this change to confirm that it has, in fact, changed. It has.

However, when I reach the print statement at the end of `nickserv.py`, the message that was sent was "IDENTIFY hunter2". The config was not changed.

Is there a way to modify the config on the fly?

If it's of any help, I've got a gist with bot.conf, bot.py, plugins/nickserv.py and my console output here: https://gist.github.com/rossjrw/75b3ecc55d4ee7d0a70b2f8e4bb879ba

Many thanks.

**Comment by fried** [comment]
Hey so nickserv component copies its password out of the config it gets.   

You don't need to make nickserv a plugin.

Create the bot like you normally would.  but before bot.run() do bot.irc_c.nickserv.password = "nothunter2"  or where ever you get it.
